In [66]:
import pandas as pd
#https://www.kaggle.com/ashirwadsangwan/imdb-dataset
# TSV (CSV/TXT) Enconding Latin1 ou Utf-8

In [67]:
#pd.read_csv('',sep = '\t', enconding) padr√£o para leitura no pandas
#definindo os caminhos dos arquivos
names = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/name.basics.tsv/name.basics.tsv', sep = "\t")
titles = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/title.akas.tsv/title.akas.tsv', sep = "\t")
titles_basic = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/title.basics.tsv/title.basics.tsv', sep = "\t")
#titles_principal = pd.read_csv('C:/Users/fic/Documents/IMDb Datasettitle.principals.tsv/title.principals.tsv', sep = "\t")
titles_rating = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/title.ratings.tsv/title.ratings.tsv', sep = "\t")

C:\Users\fic\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\fic\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [95]:
names.head(50) #Retorne as primeiras n linhas. Esta fun√ß√£o retorna as primeiras n linhas para o objeto com base na posi√ß√£o. √â √∫til para testar rapidamente se o seu objeto possui o tipo certo de dados.

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0050419,tt0053137,tt0072308,tt0043044"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0071877,tt0117057,tt0038355,tt0037382"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,producer","tt0054452,tt0049189,tt0059956,tt0057345"
3,nm0000004,John Belushi,1949,1982,"actor,writer,soundtrack","tt0077975,tt0072562,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0050976,tt0083922,tt0050986"
5,nm0000006,Ingrid Bergman,1915,1982,"actress,soundtrack,producer","tt0038109,tt0036855,tt0077711,tt0038787"
6,nm0000007,Humphrey Bogart,1899,1957,"actor,soundtrack,producer","tt0043265,tt0033870,tt0034583,tt0037382"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0070849,tt0078788,tt0044081,tt0068646"
8,nm0000009,Richard Burton,1925,1984,"actor,producer,soundtrack","tt0057877,tt0087803,tt0061184,tt0059749"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0035575,tt0031867,tt0042041,tt0029870"
10,nm0000011,Gary Cooper,1901,1961,"actor,soundtrack,producer","tt0027996,tt0034167,tt0044706,tt0035896"
11,nm0000012,Bette Davis,1908,1989,"actress,soundtrack,make_up_department","tt0031210,tt0042192,tt0056687,tt0035140"
12,nm0000013,Doris Day,1922,2019,"soundtrack,actress,producer","tt0053172,tt0055100,tt0060463,tt0048317"
13,nm0000014,Olivia de Havilland,1916,\N,"actress,soundtrack","tt0029843,tt0031381,tt0041452,tt0040806"
14,nm0000015,James Dean,1931,1955,"actor,miscellaneous","tt0048545,tt0048028,tt0043228,tt0049261"
15,nm0000016,Georges Delerue,1925,1992,"composer,soundtrack,music_department","tt0096320,tt0091763,tt0069946,tt0057345"
16,nm0000017,Marlene Dietrich,1901,1992,"soundtrack,actress,music_department","tt0051201,tt0021156,tt0055031,tt0052311"
17,nm0000018,Kirk Douglas,1916,\N,"actor,producer,soundtrack","tt0054331,tt0043338,tt0052365,tt0080736"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0053779,tt0050783,tt0071129,tt0056801"
19,nm0000020,Henry Fonda,1905,1982,"actor,producer,soundtrack","tt0082846,tt0032551,tt0064116,tt0050083"
20,nm0000021,Joan Fontaine,1917,2013,"actress,soundtrack,producer","tt0032976,tt0034248,tt0040536,tt0039504"
21,nm0000022,Clark Gable,1901,1960,"actor,soundtrack,producer","tt0025316,tt0026752,tt0052278,tt0031381"
22,nm0000023,Judy Garland,1922,1969,"soundtrack,actress","tt0055031,tt0037059,tt0047522,tt0032138"
23,nm0000024,John Gielgud,1904,2000,"actor,writer,director","tt0045943,tt0071877,tt0117631,tt0082031"
24,nm0000025,Jerry Goldsmith,1929,2004,"music_department,soundtrack,composer","tt0112715,tt0117731,tt0100802,tt0119488"
25,nm0000026,Cary Grant,1904,1986,"actor,soundtrack,producer","tt0048728,tt0053125,tt0032599,tt0056923"
26,nm0000027,Alec Guinness,1914,2000,"actor,soundtrack,writer","tt0050212,tt0076759,tt0041546,tt0051739"
27,nm0000028,Rita Hayworth,1918,1987,"actress,soundtrack,producer","tt0036723,tt0040552,tt0040525,tt0038559"
28,nm0000029,Margaux Hemingway,1954,1996,"actress,miscellaneous","tt0102122,tt0077800,tt0074802,tt0110138"
29,nm0000030,Audrey Hepburn,1929,1993,"actress,soundtrack","tt0046250,tt0054698,tt0058385,tt0056923"
30,nm0000031,Katharine Hepburn,1907,2003,"actress,soundtrack,writer","tt0063227,tt0082846,tt0032904,tt0043265"
31,nm0000032,Charlton Heston,1923,2008,"actor,director,writer","tt0052618,tt0049833,tt0070723,tt0063442"
32,nm0000033,Alfred Hitchcock,1899,1980,"actor,director,producer","tt0052357,tt0053125,tt0054215,tt0056869"
33,nm0000034,William Holden,1918,1981,"actor,soundtrack","tt0074958,tt0072308,tt0043014,tt0046359"
34,nm0000035,James Horner,1953,2015,"music_department,soundtrack,composer","tt0499549,tt0120746,tt0120647,tt0120338"
35,nm0000036,Buster Keaton,1895,1966,"actor,writer,director","tt0017925,tt0016332,tt0015324,tt0015863"
36,nm0000037,Gene Kelly,1912,1996,"actor,soundtrack,director","tt0041716,tt0043278,tt0053946,tt0045152"
37,nm0000038,Grace Kelly,1929,1982,"actress,soundtrack","tt0047396,tt0044706,tt0048728,tt0046912"
38,nm0000039,Deborah Kerr,1921,2007,"actress,soundtrack","tt0050105,tt0049408,tt0045793,tt0039192"
39,nm0000040,Stanley Kubrick,1928,1999,"director,writer,producer","tt0062622,tt0120663,tt0072684,tt0066921"
40,nm0000041,Akira Kurosawa,1910,1998,"writer,director,assistant_director","tt0051808,tt0089881,tt0080979,tt0042876"
41,nm0000042,Alan Ladd,1913,1964,"actor,producer,camera_department","tt0038369,tt0046303,tt0042279,tt0035432"
42,nm0000043,Veronica Lake,1922,1973,"actress,soundtrack,producer","tt0038369,tt0034798,tt0034881,tt0034240"
43,nm0000044,Burt Lancaster,1913,1994,"actor,producer,miscellaneous","tt0045793,tt0050468,tt0051036,tt0053793"
44,nm0000045,Bruce Lee,1940,1973,"actor,miscellaneous,producer","tt0070034,tt0068767,tt0077594,tt0068935"
45,nm0000046,Vivien Leigh,1913,1967,"actress,soundtrack,writer","tt0044081,tt0031381,tt0033238,tt0034272"
46,nm0000047,Sophia Loren,1934,\N,"actress,soundtrack","tt0058335,tt0076085,tt0060121,tt0054749"
47,nm0000048,Peter Lorre,1904,1964,"actor,soundtrack,writer","tt0022100,tt0033870,tt0034583,tt0036613"
48,nm0000049,Henry Mancini,1924,1994,"music_department,soundtrack,composer","tt0383216,tt0085101,tt0057413,tt0054698"
49,nm0000050,Groucho Marx,1890,1977,"soundtrack,actor,writer","tt0022158,tt0028772,tt0023969,tt0026778"

In [96]:
names.tail(50) # Retorne as √∫ltimas n linhas.  Esta fun√ß√£o retorna as √∫ltimas n linhas do objeto com base na posi√ß√£o. √â √∫til para verificar dados rapidamente, por exemplo, ap√≥s classificar ou anexar linhas.

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
9706872,nm9993668,Harry Traksmann,\N,\N,music_department,tt0969307
9706873,nm9993669,Valeria Malinen,\N,\N,stunts,tt0969307
9706874,nm9993670,Ken Hallen,\N,\N,stunts,tt0969307
9706875,nm9993671,Marko Lampinen,\N,\N,transportation_department,tt0969307
9706876,nm9993672,Simone Hulsemann,\N,\N,miscellaneous,tt0969307
9706877,nm9993673,Petra Jarosova,\N,\N,miscellaneous,tt0969307
9706878,nm9993674,Kerli Raag,\N,\N,miscellaneous,tt0969307
9706879,nm9993675,Ebrahim Alqazi,\N,\N,NaN,\N
9706880,nm9993676,Bonnie & The Treasures,\N,\N,NaN,\N
9706881,nm9993677,Earldine Smith,\N,\N,NaN,\N
9706882,nm9993678,Nisha Rivas Freeze,\N,\N,NaN,\N
9706883,nm9993679,Art Jones,\N,\N,director,tt8744074
9706884,nm9993680,Christopher-Lawson Palmer,\N,\N,actor,"tt10979852,tt10427366,tt8295580"
9706885,nm9993681,Saiya Palmer,\N,\N,actress,tt8295580
9706886,nm9993682,Cheryl Clark,\N,\N,actress,tt8744086
9706887,nm9993683,Lula Langston,\N,\N,actor,tt8744086
9706888,nm9993684,Angela Ng,\N,\N,miscellaneous,tt3741700
9706889,nm9993685,John Root,\N,\N,miscellaneous,tt3741700
9706890,nm9993686,Yukari Funaki,\N,\N,actress,\N
9706891,nm9993687,Hiroko Ide,\N,\N,actress,tt7170282
9706892,nm9993688,Stefania Zadra,\N,\N,miscellaneous,tt7310898
9706893,nm9993689,Chris Bailey,\N,\N,NaN,\N
9706894,nm9993690,David Jewell,\N,\N,NaN,tt7888884
9706895,nm9993691,Ursula Gehrmann,\N,\N,NaN,tt7888884
9706896,nm9993692,Shiela Martin,\N,\N,NaN,tt7888884
9706897,nm9993693,Anketa Maharana,\N,\N,actress,tt9815360
9706898,nm9993694,Chinmay Mishra,\N,\N,actor,"tt10140990,tt8737752,tt9083282,tt9097592"
9706899,nm9993696,Ibrahim-Aloduley,\N,\N,"director,editor",\N
9706900,nm9993697,Zakariya Ganim,\N,\N,actor,\N
9706901,nm9993698,Sebi John,\N,\N,actor,tt8736744
9706902,nm9993699,Dani Jacob,\N,\N,actor,tt8736744
9706903,nm9993700,Sexy Angel,\N,\N,actress,\N
9706904,nm9993701,Sanjai Kuriakose,\N,\N,actor,tt8736744
9706905,nm9993702,Liz Matory,\N,\N,NaN,\N
9706906,nm9993703,James Craigmyle,\N,\N,NaN,"tt6225166,tt6914160"
9706907,nm9993704,Wojciech Kolodziej,\N,\N,"special_effects,camera_department",\N
9706908,nm9993705,Bozena Zegert,\N,\N,make_up_department,\N
9706909,nm9993706,Michal Jackowski,\N,\N,sound_department,\N
9706910,nm9993707,Alexandra Rago,\N,\N,NaN,\N
9706911,nm9993708,Eli Bevins,\N,\N,director,"tt8744286,tt9046122"
9706912,nm9993709,Lu Bevins,\N,\N,director,tt8744286
9706913,nm9993710,Nestor Rudnytskyy,\N,\N,NaN,\N
9706914,nm9993711,David Gluzman,\N,\N,NaN,\N
9706915,nm9993712,Corny O'Connell,\N,\N,NaN,\N
9706916,nm9993713,Sambit Mishra,\N,\N,writer,tt8325250
9706917,nm9993714,Romeo del Rosario,\N,\N,"animation_department,art_department",tt2455546
9706918,nm9993716,Essias Loberg,\N,\N,NaN,\N
9706919,nm9993717,Harikrishnan Rajan,\N,\N,cinematographer,tt8736744
9706920,nm9993718,Aayush Nair,\N,\N,cinematographer,\N
9706921,nm9993719,Andre Hill,\N,\N,NaN,\N

In [70]:
names.describe()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
count,9706922,9706922,9706922,9706922,7775897,9706922
unique,9706922,7618021,481,422,19674,4036203
top,nm2119953,David Smith,\N,\N,actor,\N
freq,1,310,9215641,9534917,1772491,1689596

In [94]:
titles_basic.head(50)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,\N,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
5,tt0000006,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,Short
6,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport"
7,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short"
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
9,tt0000010,short,Exiting the Factory,La sortie de l'usine Lumi√®re √† Lyon,0,1895,\N,1,"Documentary,Short"
10,tt0000011,short,Akrobatisches Potpourri,Akrobatisches Potpourri,0,1895,\N,1,"Documentary,Short"
11,tt0000012,short,The Arrival of a Train,L'arriv√©e d'un train √† La Ciotat,0,1896,\N,1,"Action,Documentary,Short"
12,tt0000013,short,The Photographical Congress Arrives in Lyon,Neuville-sur-Sa√¥ne: D√©barquement du congr√®s de...,0,1895,\N,1,"Documentary,Short"
13,tt0000014,short,The Sprinkler Sprinkled,L'arroseur arros√©,0,1895,\N,1,"Comedy,Short"
14,tt0000015,short,Autour d'une cabine,Autour d'une cabine,0,1894,\N,2,"Animation,Short"
15,tt0000016,short,Barque sortant du port,Barque sortant du port,0,1895,\N,1,"Documentary,Short"
16,tt0000017,short,Italienischer Bauerntanz,Italienischer Bauerntanz,0,1895,\N,1,"Documentary,Short"
17,tt0000018,short,Das boxende K√§nguruh,Das boxende K√§nguruh,0,1895,\N,1,Short
18,tt0000019,short,The Clown Barber,The Clown Barber,0,1898,\N,\N,"Comedy,Short"
19,tt0000020,short,The Derby 1895,The Derby 1895,0,1895,\N,1,"Documentary,Short,Sport"
20,tt0000022,short,Blacksmith Scene,Les forgerons,0,1895,\N,1,"Documentary,Short"
21,tt0000023,short,The Sea,Baignade en mer,0,1895,\N,1,"Documentary,Short"
22,tt0000024,short,Opening of the Kiel Canal,Opening of the Kiel Canal,0,1895,\N,\N,"News,Short"
23,tt0000025,short,The Oxford and Cambridge University Boat Race,The Oxford and Cambridge University Boat Race,0,1895,\N,\N,"News,Short,Sport"
24,tt0000026,short,The Messers. Lumi√®re at Cards,Partie d'√©cart√©,0,1896,\N,1,"Documentary,Short"
25,tt0000027,short,Cordeliers' Square in Lyon,Place des Cordeliers √† Lyon,0,1895,\N,1,"Documentary,Short"
26,tt0000028,short,Fishing for Goldfish,La p√™che aux poissons rouges,0,1895,\N,1,"Documentary,Short"
27,tt0000029,short,Baby's Dinner,Repas de b√©b√©,0,1895,\N,1,"Documentary,Short"
28,tt0000030,short,Rough Sea at Dover,Rough Sea at Dover,0,1895,\N,1,"Documentary,Short"
29,tt0000031,short,Jumping the Blanket,Le saut √† la couverture,0,1895,\N,1,"Documentary,Short"
30,tt0000032,short,Die Serpentint√§nzerin,Die Serpentint√§nzerin,0,1895,\N,1,Short
31,tt0000033,short,Trick Riding,La voltige,0,1895,\N,1,"Comedy,Documentary,Short"
32,tt0000034,short,Arriv√©e d'un train gare de Vincennes,Arriv√©e d'un train gare de Vincennes,0,1896,\N,1,"Documentary,Short"
33,tt0000035,short,Watering the Flowers,L'arroseur,0,1896,\N,1,"Comedy,Short"
34,tt0000036,short,Awakening of Rip,Awakening of Rip,0,1896,\N,0,"Drama,Short"
35,tt0000037,short,Sea Bathing,Baignade en mer,0,1896,\N,1,Short
36,tt0000038,short,The Ball Game,The Ball Game,0,1898,\N,\N,"Documentary,Short,Sport"
37,tt0000039,short,Barnet Horse Fair,Barnet Horse Fair,0,1896,\N,\N,Short
38,tt0000040,short,Barque sortant du port de Trouville,Barque sortant du port de Trouville,0,1896,\N,\N,"Documentary,Short"
39,tt0000041,short,Bataille de neige,Bataille de neige,0,1897,\N,1,"Action,Comedy,Documentary"
40,tt0000042,short,Bateau-mouche sur la Seine,Bateau-mouche sur la Seine,0,1896,\N,\N,"Documentary,Short"
41,tt0000043,short,Batteuse √† vapeur,Batteuse √† vapeur,0,1896,\N,\N,"Documentary,Short"
42,tt0000044,short,Le bivouac,Le bivouac,0,1896,\N,1,Short
43,tt0000045,short,Les blanchisseuses,Les blanchisseuses,0,1896,\N,\N,Short
44,tt0000046,short,Bois de Boulogne,Bois de Boulogne,0,1896,\N,\N,"Documentary,Short"
45,tt0000047,short,Boulevard des Italiens,Boulevard des Italiens,0,1896,\N,\N,"Documentary,Short"
46,tt0000048,short,The Boxing Kangaroo,The Boxing Kangaroo,0,1896,\N,\N,Short
47,tt0000049,short,"Boxing Match; or, Glove Contest","Boxing Match; or, Glove Contest",0,1896,\N,\N,"Short,Sport"
48,tt0000050,short,B√©b√© et fillettes,B√©b√© et fillettes,0,1896,\N,\N,"Documentary,Short"
49,tt0000051,short,The Bohemian Encampment,Campement de boh√©miens,0,1896,\N,\N,"Documentary,Short"

In [93]:
titles_basic.tail(50)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
6321252,tt9916754,movie,Chico Albuquerque - Revela√ß√µes,Chico Albuquerque - Revela√ß√µes,0,2013,\N,\N,Documentary
6321253,tt9916756,short,Pretty Pretty Black Girl,Pretty Pretty Black Girl,0,2019,\N,\N,Short
6321254,tt9916758,tvEpisode,Willy Naessens,Willy Naessens,0,2019,\N,\N,"Comedy,News,Talk-Show"
6321255,tt9916760,tvEpisode,Episode #2.21,Episode #2.21,0,2009,\N,\N,"Action,Drama,Family"
6321256,tt9916762,tvEpisode,Episode #2.22,Episode #2.22,0,2009,\N,\N,"Action,Drama,Family"
6321257,tt9916764,short,38,38,0,2018,\N,\N,Short
6321258,tt9916766,tvEpisode,Episode #10.15,Episode #10.15,0,2019,\N,43,"Family,Reality-TV"
6321259,tt9916768,tvEpisode,Episode #2.23,Episode #2.23,0,2009,\N,\N,"Action,Drama,Family"
6321260,tt9916770,tvEpisode,Episode #2.24,Episode #2.24,0,2009,\N,\N,"Action,Drama,Family"
6321261,tt9916774,tvEpisode,Episode #2.25,Episode #2.25,0,2009,\N,\N,"Action,Drama,Family"
6321262,tt9916776,tvEpisode,Talent Coaching with IMOR's Bianca Desmore Mit...,Talent Coaching with IMOR's Bianca Desmore Mit...,0,2019,\N,\N,Talk-Show
6321263,tt9916778,tvEpisode,Escape,Escape,0,2019,\N,\N,Drama
6321264,tt9916780,tvEpisode,Episode #2.26,Episode #2.26,0,2009,\N,\N,"Action,Drama,Family"
6321265,tt9916782,tvEpisode,Episode #2.27,Episode #2.27,0,2009,\N,\N,"Action,Drama,Family"
6321266,tt9916784,tvEpisode,Episode #2.28,Episode #2.28,0,2009,\N,\N,"Action,Drama,Family"
6321267,tt9916786,tvEpisode,Episode #2.29,Episode #2.29,0,2009,\N,\N,"Action,Drama,Family"
6321268,tt9916788,tvEpisode,Episode #2.30,Episode #2.30,0,2009,\N,\N,"Action,Drama,Family"
6321269,tt9916790,tvEpisode,Tinne Oltmans,Tinne Oltmans,0,2019,\N,\N,"Comedy,News,Talk-Show"
6321270,tt9916792,tvEpisode,Episode #2.32,Episode #2.32,0,2009,\N,\N,"Action,Drama,Family"
6321271,tt9916794,tvEpisode,Episode #2.33,Episode #2.33,0,2009,\N,\N,"Action,Drama,Family"
6321272,tt9916796,tvEpisode,Episode #2.34,Episode #2.34,0,2009,\N,\N,"Action,Drama,Family"
6321273,tt9916798,tvEpisode,Episode #2.36,Episode #2.36,0,2009,\N,\N,"Action,Drama,Family"
6321274,tt9916800,tvEpisode,Episode #2.35,Episode #2.35,0,2009,\N,\N,"Action,Drama,Family"
6321275,tt9916802,tvEpisode,Luc Janssens,Luc Janssens,0,2019,\N,\N,"Comedy,News,Talk-Show"
6321276,tt9916804,tvEpisode,Episode #2.37,Episode #2.37,0,2009,\N,\N,"Action,Drama,Family"
6321277,tt9916806,tvEpisode,Episode #3.1,Episode #3.1,0,2010,\N,\N,"Action,Drama,Family"
6321278,tt9916808,tvEpisode,Episode #3.2,Episode #3.2,0,2010,\N,\N,"Action,Drama,Family"
6321279,tt9916810,tvEpisode,Danira Boukhriss Terkessidis,Danira Boukhriss Terkessidis,0,2019,\N,\N,"Comedy,News,Talk-Show"
6321280,tt9916812,tvEpisode,Episode #3.3,Episode #3.3,0,2010,\N,\N,"Action,Drama,Family"
6321281,tt9916814,tvEpisode,Episode #3.4,Episode #3.4,0,2010,\N,\N,"Action,Drama,Family"
6321282,tt9916816,tvEpisode,Episode #3.5,Episode #3.5,0,2010,\N,\N,"Action,Drama,Family"
6321283,tt9916818,tvEpisode,Episode #3.6,Episode #3.6,0,2010,\N,\N,"Action,Drama,Family"
6321284,tt9916820,tvEpisode,Episode #3.7,Episode #3.7,0,2010,\N,\N,"Action,Drama,Family"
6321285,tt9916822,tvEpisode,Episode #3.8,Episode #3.8,0,2010,\N,\N,"Action,Drama,Family"
6321286,tt9916824,tvEpisode,Episode #3.9,Episode #3.9,0,2010,\N,\N,"Action,Drama,Family"
6321287,tt9916826,tvEpisode,Episode #3.10,Episode #3.10,0,2010,\N,\N,"Action,Drama,Family"
6321288,tt9916830,tvEpisode,Episode #2.6,Episode #2.6,0,1973,\N,\N,Game-Show
6321289,tt9916832,tvEpisode,Episode #3.11,Episode #3.11,0,2010,\N,\N,"Action,Drama,Family"
6321290,tt9916834,tvEpisode,Episode #3.12,Episode #3.12,0,2010,\N,\N,"Action,Drama,Family"
6321291,tt9916836,tvEpisode,Episode #3.14,Episode #3.14,0,2010,\N,\N,"Action,Drama,Family"
6321292,tt9916838,tvEpisode,Episode #3.13,Episode #3.13,0,2010,\N,\N,"Action,Drama,Family"
6321293,tt9916840,tvEpisode,Horrid Henry's Comic Caper,Horrid Henry's Comic Caper,0,2014,\N,11,"Animation,Comedy,Family"
6321294,tt9916842,tvEpisode,Episode #3.16,Episode #3.16,0,2010,\N,\N,"Action,Drama,Family"
6321295,tt9916844,tvEpisode,Episode #3.15,Episode #3.15,0,2010,\N,\N,"Action,Drama,Family"
6321296,tt9916846,tvEpisode,Episode #3.18,Episode #3.18,0,2010,\N,\N,"Action,Drama,Family"
6321297,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2010,\N,\N,"Action,Drama,Family"
6321298,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
6321299,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
6321300,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
6321301,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Animation,Comedy,Family"

In [73]:
titles_basic.describe()

            isAdult
count  6.321302e+06
mean   3.309176e-02
std    2.537068e+00
min    0.000000e+00
25%    0.000000e+00
50%    0.000000e+00
75%    0.000000e+00
max    2.019000e+03

In [74]:
titles_basic['titleType'].unique() # saber quais s√£o os dados unicos que tem na tabela Basic Retorne valores exclusivos no √≠ndice. Os itens √∫nicos s√£o retornados em ordem de apar√™ncia, isso N√ÉO classifica.

array(['short', 'movie', 'tvMovie', 'tvSeries', 'tvEpisode', 'tvShort',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame'], dtype=object)

In [75]:
titles_rating.head(5)

      tconst  averageRating  numVotes
0  tt0000001            5.6      1550
1  tt0000002            6.1       186
2  tt0000003            6.5      1207
3  tt0000004            6.2       113
4  tt0000005            6.1      1934

In [132]:
titles_sliced = titles_basic.iloc[:,[0,1,2,8]]  #minimizar a tabela para uma visualiza√ß√£o curta, com
titles_sliced.head(5)

      tconst titleType            primaryTitle                    genres
0  tt0000001     short              Carmencita         Documentary,Short
1  tt0000002     short  Le clown et ses chiens           Animation,Short
2  tt0000003     short          Pauvre Pierrot  Animation,Comedy,Romance
3  tt0000004     short             Un bon bock           Animation,Short
4  tt0000005     short        Blacksmith Scene              Comedy,Short

In [133]:
titles_sliced.columns = ['tconst','tipo', 'titulo', 'genero']  ###renomear o nome das colunas com a fun√ß√£o Columns 
titles_sliced.head(5)

      tconst   tipo                  titulo                    genero
0  tt0000001  short              Carmencita         Documentary,Short
1  tt0000002  short  Le clown et ses chiens           Animation,Short
2  tt0000003  short          Pauvre Pierrot  Animation,Comedy,Romance
3  tt0000004  short             Un bon bock           Animation,Short
4  tt0000005  short        Blacksmith Scene              Comedy,Short

In [106]:
titles_rating_merge = titles_rating.merge(titles_sliced, left_on = 'tconst', right_on = 'tconst') # fazendo a jun√ß√£o das tabelas com Merge, utilizando a coluna TCONST como chave primaria   
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge.html?highlight=merge#pandas.merge
titles_rating_merge.head(5)

,tconst,averageRating,numVotes,tipo,titulo,genero
0,tt0000001,5.6,1550,short,Carmencita,"Documentary,Short"
1,tt0000002,6.1,186,short,Le clown et ses chiens,"Animation,Short"
2,tt0000003,6.5,1207,short,Pauvre Pierrot,"Animation,Comedy,Romance"
3,tt0000004,6.2,113,short,Un bon bock,"Animation,Short"
4,tt0000005,6.1,1934,short,Blacksmith Scene,"Comedy,Short"

In [107]:
titles_rating_merge.sort_values(by =['numVotes'], ascending=False).head(100) # fa√ßa a ordena√ß√£o da coluna NUMVOTES do maior para o menor e imprima as 30 primeiras linhas
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html?highlight=sort_values

,tconst,averageRating,numVotes,tipo,titulo,genero
80579,tt0111161,9.3,2159745,movie,The Shawshank Redemption,Drama
241008,tt0468569,9.0,2134602,movie,The Dark Knight,"Action,Crime,Drama"
515622,tt1375666,8.8,1892958,movie,Inception,"Action,Adventure,Sci-Fi"
96689,tt0137523,8.8,1725444,movie,Fight Club,Drama
80363,tt0110912,8.9,1695159,movie,Pulp Fiction,"Crime,Drama"
79501,tt0109830,8.8,1662609,movie,Forrest Gump,"Drama,Romance"
413358,tt0944947,9.4,1606096,tvSeries,Game of Thrones,"Action,Adventure,Drama"
94660,tt0133093,8.7,1554345,movie,The Matrix,"Action,Sci-Fi"
88334,tt0120737,8.8,1548920,movie,The Lord of the Rings: The Fellowship of the Ring,"Adventure,Drama,Fantasy"
111186,tt0167260,8.9,1533632,movie,The Lord of the Rings: The Return of the King,"Adventure,Drama,Fantasy"
44727,tt0068646,9.2,1482225,movie,The Godfather,"Crime,Drama"
509867,tt1345836,8.4,1421506,movie,The Dark Knight Rises,"Action,Thriller"
111187,tt0167261,8.7,1387208,movie,The Lord of the Rings: The Two Towers,"Adventure,Drama,Fantasy"
378552,tt0816692,8.6,1348184,movie,Interstellar,"Adventure,Drama,Sci-Fi"
83129,tt0114369,8.6,1327441,movie,Se7en,"Crime,Drama,Mystery"
403836,tt0903747,9.5,1280143,tvSeries,Breaking Bad,"Crime,Drama,Thriller"
596786,tt1853728,8.4,1249336,movie,Django Unchained,"Drama,Western"
113555,tt0172495,8.5,1246819,movie,Gladiator,"Action,Adventure,Drama"
201998,tt0372784,8.2,1225060,movie,Batman Begins,"Action,Adventure"
388847,tt0848228,8.0,1206913,movie,The Avengers,"Action,Adventure,Sci-Fi"
73829,tt0102926,8.6,1169847,movie,The Silence of the Lambs,"Crime,Drama,Thriller"
197060,tt0361748,8.3,1162262,movie,Inglourious Basterds,"Adventure,Drama,War"
51609,tt0076759,8.6,1147264,movie,Star Wars: Episode IV - A New Hope,"Action,Adventure,Fantasy"
88396,tt0120815,8.6,1143793,movie,Saving Private Ryan,"Drama,War"
78033,tt0108052,8.9,1120297,movie,Schindler's List,"Biography,Drama,History"
217274,tt0407887,8.5,1104064,movie,The Departed,"Crime,Drama,Thriller"
246819,tt0482571,8.5,1095266,movie,The Prestige,"Drama,Mystery,Sci-Fi"
54964,tt0080684,8.7,1078754,movie,Star Wars: Episode V - The Empire Strikes Back,"Action,Adventure,Fantasy"
424947,tt0993846,8.2,1069874,movie,The Wolf of Wall Street,"Biography,Crime,Drama"
253005,tt0499549,7.8,1066615,movie,Avatar,"Action,Adventure,Fantasy"
...,...,...,...,...,...,...
649053,tt2267998,8.1,784465,movie,Gone Girl,"Drama,Mystery,Thriller"
126486,tt0198781,8.0,760273,movie,"Monsters, Inc.","Adventure,Animation,Comedy"
429650,tt1010048,8.0,759588,movie,Slumdog Millionaire,"Drama,Romance"
61356,tt0088247,8.0,751700,movie,The Terminator,"Action,Sci-Fi"
154897,tt0264464,8.1,745335,movie,Catch Me If You Can,"Biography,Crime,Drama"
67160,tt0095016,8.2,735223,movie,Die Hard,"Action,Thriller"
130653,tt0208092,8.3,734562,movie,Snatch,"Comedy,Crime"
532643,tt1475582,9.1,733933,tvSeries,Sherlock,"Crime,Drama,Mystery"
53318,tt0078748,8.4,733661,movie,Alien,"Horror,Sci-Fi"
403805,tt0903624,7.8,728476,movie,The Hobbit: An Unexpected Journey,"Adventure,Family,Fantasy"
528899,tt1454468,7.7,725671,movie,Gravity,"Drama,Sci-Fi,Thriller"
769375,tt4154756,8.5,725112,movie,Avengers: Infinity War,"Action,Adventure,Sci-Fi"
214884,tt0401792,8.0,721717,movie,Sin City,"Crime,Thriller"
117191,tt0180093,8.3,716729,movie,Requiem for a Dream,Drama
78611,tt0108778,8.9,715485,tvSeries,Friends,"Comedy,Romance"
500204,tt1300854,7.2,711617,movie,Iron Man 3,"Action,Adventure,Sci-Fi"
146970,tt0246578,8.0,708866,movie,Donnie Darko,"Drama,Sci-Fi,Thriller"
479730,tt1201607,8.1,708388,movie,Harry Potter and the Deathly Hallows: Part 2,"Adventure,Drama,Fantasy"
43203,tt0066921,8.3,707611,movie,A Clockwork Orange,"Crime,Drama,Sci-Fi"
228642,tt0435761,8.3,707372,movie,Toy Story 3,"Adventure,Animation,Comedy"
220585,tt0416449,7.7,702798,movie,300,"Action,Drama,Fantasy"
372970,tt0800369,7.0,702396,movie,Thor,"Action,Adventure,Fantasy"
742704,tt3659388,8.0,701746,movie,The Martian,"Adventure,Drama,Sci-Fi"
567765,tt1675434,8.5,698385,movie,The Intouchables,"Biography,Comedy,Drama"
665182,tt2395427,7.3,688963,movie,Avengers: Age of Ultron,"Action,Adventure,Sci-Fi"
237413,tt0458339,6.9,688918,movie,Captain America: The First Avenger,"Action,Adventure,Sci-Fi"
595152,tt1843866,7.7,687645,movie,Captain America: The Winter Soldier,"Action,Adventure,Sci-Fi"
59681,tt0086250,8.3,682563,movie,Scarface,"Crime,Drama"
480508,tt1205489,8.1,682498,movie,Gran Torino,Drama
464629,tt1119646,7.7,682340,movie,The Hangover,Comedy

In [108]:
top = titles_rating_merge[(titles_rating_merge['numVotes'] > 50000) & (titles_rating_merge['tipo'] == 'movie')].sort_values(by =['averageRating'], ascending=False).head(50)
top

,tconst,averageRating,numVotes,tipo,titulo,genero
80579,tt0111161,9.3,2159745,movie,The Shawshank Redemption,Drama
44727,tt0068646,9.2,1482225,movie,The Godfather,"Crime,Drama"
47237,tt0071562,9.0,1032110,movie,The Godfather: Part II,"Crime,Drama"
854299,tt5813916,9.0,101817,movie,The Mountain II,"Action,Drama,War"
241008,tt0468569,9.0,2134602,movie,The Dark Knight,"Action,Crime,Drama"
78033,tt0108052,8.9,1120297,movie,Schindler's List,"Biography,Drama,History"
80363,tt0110912,8.9,1695159,movie,Pulp Fiction,"Crime,Drama"
28825,tt0050083,8.9,617607,movie,12 Angry Men,Drama
111186,tt0167260,8.9,1533632,movie,The Lord of the Rings: The Return of the King,"Adventure,Drama,Fantasy"
96689,tt0137523,8.8,1725444,movie,Fight Club,Drama
79501,tt0109830,8.8,1662609,movie,Forrest Gump,"Drama,Romance"
88334,tt0120737,8.8,1548920,movie,The Lord of the Rings: The Fellowship of the Ring,"Adventure,Drama,Fantasy"
515622,tt1375666,8.8,1892958,movie,Inception,"Action,Adventure,Sci-Fi"
37522,tt0060196,8.8,640941,movie,"The Good, the Bad and the Ugly",Western
921072,tt7286456,8.8,466912,movie,Joker,"Crime,Drama,Thriller"
94660,tt0133093,8.7,1554345,movie,The Matrix,"Action,Sci-Fi"
48858,tt0073486,8.7,852798,movie,One Flew Over the Cuckoo's Nest,Drama
71146,tt0099685,8.7,933687,movie,Goodfellas,"Biography,Crime,Drama"
54964,tt0080684,8.7,1078754,movie,Star Wars: Episode V - The Empire Strikes Back,"Action,Adventure,Fantasy"
111187,tt0167261,8.7,1387208,movie,The Lord of the Rings: The Two Towers,"Adventure,Drama,Fantasy"
898922,tt6751668,8.6,73962,movie,Parasite,"Comedy,Drama,Thriller"
88396,tt0120815,8.6,1143793,movie,Saving Private Ryan,"Drama,War"
88300,tt0120689,8.6,1050158,movie,The Green Mile,"Crime,Drama,Fantasy"
86711,tt0118799,8.6,570765,movie,Life Is Beautiful,"Comedy,Drama,Romance"
19591,tt0038650,8.6,366750,movie,It's a Wonderful Life,"Drama,Family,Fantasy"
378552,tt0816692,8.6,1348184,movie,Interstellar,"Adventure,Drama,Sci-Fi"
83129,tt0114369,8.6,1327441,movie,Se7en,"Crime,Drama,Mystery"
51609,tt0076759,8.6,1147264,movie,Star Wars: Episode IV - A New Hope,"Action,Adventure,Fantasy"
180146,tt0317248,8.6,659285,movie,City of God,"Crime,Drama"
523972,tt1424432,8.6,56850,movie,Senna,"Biography,Documentary,Sport"
26658,tt0047478,8.6,292241,movie,Seven Samurai,"Action,Adventure,Drama"
73829,tt0102926,8.6,1169847,movie,The Silence of the Lambs,"Crime,Drama,Thriller"
146408,tt0245429,8.6,577038,movie,Spirited Away,"Adventure,Animation,Family"
83480,tt0114814,8.5,928556,movie,The Usual Suspects,"Crime,Mystery,Thriller"
79959,tt0110413,8.5,955335,movie,L√©on: The Professional,"Action,Crime,Drama"
79910,tt0110357,8.5,871796,movie,The Lion King,"Adventure,Animation,Drama"
246819,tt0482571,8.5,1095266,movie,The Prestige,"Drama,Mystery,Sci-Fi"
73941,tt0103064,8.5,934836,movie,Terminator 2: Judgment Day,"Action,Sci-Fi"
113555,tt0172495,8.5,1246819,movie,Gladiator,"Action,Adventure,Drama"
61793,tt0088763,8.5,965539,movie,Back to the Future,"Adventure,Comedy,Sci-Fi"
32354,tt0054215,8.5,555275,movie,Psycho,"Horror,Mystery,Thriller"
88225,tt0120586,8.5,973841,movie,American History X,Drama
11145,tt0027977,8.5,197987,movie,Modern Times,"Comedy,Drama,Family"
40809,tt0064116,8.5,279260,movie,Once Upon a Time in the West,Western
567765,tt1675434,8.5,698385,movie,The Intouchables,"Biography,Comedy,Drama"
6667,tt0021749,8.5,152730,movie,City Lights,"Comedy,Drama,Romance"
149942,tt0253474,8.5,665195,movie,The Pianist,"Biography,Drama,Music"
16339,tt0034583,8.5,487781,movie,Casablanca,"Drama,Romance,War"
217274,tt0407887,8.5,1104064,movie,The Departed,"Crime,Drama,Thriller"
14675,tt0032553,8.5,186657,movie,The Great Dictator,"Comedy,Drama,War"

In [109]:
top1 = titles_rating_merge[(titles_rating_merge['tipo'] == 'movie')].sort_values(by =['numVotes'], ascending=False).head(50)
top1

,tconst,averageRating,numVotes,tipo,titulo,genero
80579,tt0111161,9.3,2159745,movie,The Shawshank Redemption,Drama
241008,tt0468569,9.0,2134602,movie,The Dark Knight,"Action,Crime,Drama"
515622,tt1375666,8.8,1892958,movie,Inception,"Action,Adventure,Sci-Fi"
96689,tt0137523,8.8,1725444,movie,Fight Club,Drama
80363,tt0110912,8.9,1695159,movie,Pulp Fiction,"Crime,Drama"
79501,tt0109830,8.8,1662609,movie,Forrest Gump,"Drama,Romance"
94660,tt0133093,8.7,1554345,movie,The Matrix,"Action,Sci-Fi"
88334,tt0120737,8.8,1548920,movie,The Lord of the Rings: The Fellowship of the Ring,"Adventure,Drama,Fantasy"
111186,tt0167260,8.9,1533632,movie,The Lord of the Rings: The Return of the King,"Adventure,Drama,Fantasy"
44727,tt0068646,9.2,1482225,movie,The Godfather,"Crime,Drama"
509867,tt1345836,8.4,1421506,movie,The Dark Knight Rises,"Action,Thriller"
111187,tt0167261,8.7,1387208,movie,The Lord of the Rings: The Two Towers,"Adventure,Drama,Fantasy"
378552,tt0816692,8.6,1348184,movie,Interstellar,"Adventure,Drama,Sci-Fi"
83129,tt0114369,8.6,1327441,movie,Se7en,"Crime,Drama,Mystery"
596786,tt1853728,8.4,1249336,movie,Django Unchained,"Drama,Western"
113555,tt0172495,8.5,1246819,movie,Gladiator,"Action,Adventure,Drama"
201998,tt0372784,8.2,1225060,movie,Batman Begins,"Action,Adventure"
388847,tt0848228,8.0,1206913,movie,The Avengers,"Action,Adventure,Sci-Fi"
73829,tt0102926,8.6,1169847,movie,The Silence of the Lambs,"Crime,Drama,Thriller"
197060,tt0361748,8.3,1162262,movie,Inglourious Basterds,"Adventure,Drama,War"
51609,tt0076759,8.6,1147264,movie,Star Wars: Episode IV - A New Hope,"Action,Adventure,Fantasy"
88396,tt0120815,8.6,1143793,movie,Saving Private Ryan,"Drama,War"
78033,tt0108052,8.9,1120297,movie,Schindler's List,"Biography,Drama,History"
217274,tt0407887,8.5,1104064,movie,The Departed,"Crime,Drama,Thriller"
246819,tt0482571,8.5,1095266,movie,The Prestige,"Drama,Mystery,Sci-Fi"
54964,tt0080684,8.7,1078754,movie,Star Wars: Episode V - The Empire Strikes Back,"Action,Adventure,Fantasy"
424947,tt0993846,8.2,1069874,movie,The Wolf of Wall Street,"Biography,Crime,Drama"
253005,tt0499549,7.8,1066615,movie,Avatar,"Action,Adventure,Fantasy"
131112,tt0209144,8.4,1052917,movie,Memento,"Mystery,Thriller"
88300,tt0120689,8.6,1050158,movie,The Green Mile,"Crime,Drama,Fantasy"
466782,tt1130884,8.1,1036341,movie,Shutter Island,"Mystery,Thriller"
47237,tt0071562,9.0,1032110,movie,The Godfather: Part II,"Crime,Drama"
112346,tt0169547,8.3,1009428,movie,American Beauty,Drama
616906,tt2015381,8.0,980782,movie,Guardians of the Galaxy,"Action,Adventure,Comedy"
88024,tt0120338,7.8,980721,movie,Titanic,"Drama,Romance"
183827,tt0325980,8.0,977322,movie,Pirates of the Caribbean: The Curse of the Bla...,"Action,Adventure,Fantasy"
88225,tt0120586,8.5,973841,movie,American History X,Drama
228143,tt0434409,8.2,971070,movie,V for Vendetta,"Action,Drama,Sci-Fi"
61793,tt0088763,8.5,965539,movie,Back to the Future,"Adventure,Comedy,Sci-Fi"
79959,tt0110413,8.5,955335,movie,L√©on: The Professional,"Action,Crime,Drama"
73941,tt0103064,8.5,934836,movie,Terminator 2: Judgment Day,"Action,Sci-Fi"
71146,tt0099685,8.7,933687,movie,Goodfellas,"Biography,Crime,Drama"
155808,tt0266697,8.1,932267,movie,Kill Bill: Vol. 1,"Action,Crime,Thriller"
405651,tt0910970,8.4,931389,movie,WALL¬∑E,"Adventure,Animation,Family"
83480,tt0114814,8.5,928556,movie,The Usual Suspects,"Crime,Mystery,Thriller"
81684,tt0112573,8.3,908996,movie,Braveheart,"Biography,Drama,History"
155754,tt0266543,8.1,889815,movie,Finding Nemo,"Adventure,Animation,Comedy"
201544,tt0371746,7.9,887188,movie,Iron Man,"Action,Adventure,Sci-Fi"
59625,tt0086190,8.3,882793,movie,Star Wars: Episode VI - Return of the Jedi,"Action,Adventure,Fantasy"
79910,tt0110357,8.5,871796,movie,The Lion King,"Adventure,Animation,Drama"

In [119]:
top2 = top.groupby(['tipo', 'genero']).agg({'numVotes':'sum'}) #contru√ß√£o da tabela dinamica , pivotagem
top2

                                   numVotes
tipo  genero
movie Action,Adventure,Drama        1539060
      Action,Adventure,Fantasy      2226018
      Action,Adventure,Sci-Fi       1892958
      Action,Crime,Drama            3089937
      Action,Drama,War               101817
      Action,Sci-Fi                 2489181
      Adventure,Animation,Drama      871796
      Adventure,Animation,Family     577038
      Adventure,Comedy,Sci-Fi        965539
      Adventure,Drama,Fantasy       4469760
      Adventure,Drama,Sci-Fi        1348184
      Biography,Comedy,Drama         698385
      Biography,Crime,Drama          933687
      Biography,Documentary,Sport     56850
      Biography,Drama,History       1120297
      Biography,Drama,Music          665195
      Comedy,Drama,Family            197987
      Comedy,Drama,Romance           723495
      Comedy,Drama,Thriller           73962
      Comedy,Drama,War               186657
      Crime,Drama                   4868779
      Crime,Drama,Fantasy           1050158
      Crime,Drama,Mystery           1327441
      Crime,Drama,Thriller          2740823
      Crime,Mystery,Thriller         928556
      Drama                         6329435
      Drama,Family,Fantasy           366750
      Drama,Mystery,Sci-Fi          1095266
      Drama,Romance                 1662609
      Drama,Romance,War              487781
      Drama,War                     1143793
      Horror,Mystery,Thriller        555275
      Western                        920201

In [118]:
top3 = top.groupby(['tipo','titulo']).agg({'numVotes':'sum'})
top3

                                                         numVotes
tipo  titulo
movie 12 Angry Men                                         617607
      American History X                                   973841
      Back to the Future                                   965539
      Casablanca                                           487781
      City Lights                                          152730
      City of God                                          659285
      Fight Club                                          1725444
      Forrest Gump                                        1662609
      Gladiator                                           1246819
      Goodfellas                                           933687
      Inception                                           1892958
      Interstellar                                        1348184
      It's a Wonderful Life                                366750
      Joker                                                466912
      Life Is Beautiful                                    570765
      L√©on: The Professional                               955335
      Modern Times                                         197987
      Once Upon a Time in the West                         279260
      One Flew Over the Cuckoo's Nest                      852798
      Parasite                                              73962
      Psycho                                               555275
      Pulp Fiction                                        1695159
      Saving Private Ryan                                 1143793
      Schindler's List                                    1120297
      Se7en                                               1327441
      Senna                                                 56850
      Seven Samurai                                        292241
      Spirited Away                                        577038
      Star Wars: Episode IV - A New Hope                  1147264
      Star Wars: Episode V - The Empire Strikes Back      1078754
      Terminator 2: Judgment Day                           934836
      The Dark Knight                                     2134602
      The Departed                                        1104064
      The Godfather                                       1482225
      The Godfather: Part II                              1032110
      The Good, the Bad and the Ugly                       640941
      The Great Dictator                                   186657
      The Green Mile                                      1050158
      The Intouchables                                     698385
      The Lion King                                        871796
      The Lord of the Rings: The Fellowship of the Ring   1548920
      The Lord of the Rings: The Return of the King       1533632
      The Lord of the Rings: The Two Towers               1387208
      The Matrix                                          1554345
      The Mountain II                                      101817
      The Pianist                                          665195
      The Prestige                                        1095266
      The Shawshank Redemption                            2159745
      The Silence of the Lambs                            1169847
      The Usual Suspects                                   928556

In [125]:
top_pcts = top3.groupby(level = 0).apply(lambda x: 100 * x / float(x.sum()))
top_pcts.sort_values(by = ['numVotes'], ascending = False)

                                                         numVotes
tipo  titulo
movie The Shawshank Redemption                           4.527324
      The Dark Knight                                    4.474619
      Inception                                          3.968077
      Fight Club                                         3.616929
      Pulp Fiction                                       3.553445
      Forrest Gump                                       3.485212
      The Matrix                                         3.258266
      The Lord of the Rings: The Fellowship of the Ring  3.246894
      The Lord of the Rings: The Return of the King      3.214847
      The Godfather                                      3.107086
      The Lord of the Rings: The Two Towers              2.907908
      Interstellar                                       2.826105
      Se7en                                              2.782623
      Gladiator                                          2.613620
      The Silence of the Lambs                           2.452269
      Star Wars: Episode IV - A New Hope                 2.404930
      Saving Private Ryan                                2.397654
      Schindler's List                                   2.348401
      The Departed                                       2.314373
      The Prestige                                       2.295930
      Star Wars: Episode V - The Empire Strikes Back     2.261317
      The Green Mile                                     2.201374
      The Godfather: Part II                             2.163541
      American History X                                 2.041396
      Back to the Future                                 2.023993
      L√©on: The Professional                             2.002603
      Terminator 2: Judgment Day                         1.959632
      Goodfellas                                         1.957223
      The Usual Suspects                                 1.946468
      The Lion King                                      1.827486
      One Flew Over the Cuckoo's Nest                    1.787661
      The Intouchables                                   1.463976
      The Pianist                                        1.394402
      City of God                                        1.382014
      The Good, the Bad and the Ugly                     1.343560
      12 Angry Men                                       1.294647
      Spirited Away                                      1.209605
      Life Is Beautiful                                  1.196455
      Psycho                                             1.163985
      Casablanca                                         1.022502
      Joker                                              0.978755
      It's a Wonderful Life                              0.768793
      Seven Samurai                                      0.612605
      Once Upon a Time in the West                       0.585393
      Modern Times                                       0.415026
      The Great Dictator                                 0.391276
      City Lights                                        0.320157
      The Mountain II                                    0.213432
      Parasite                                           0.155041
      Senna                                              0.119171

In [149]:
titles_sliced = titles_basic.iloc[:,[0,1,2,8]]  #minimizar a tabela para uma visualiza√ß√£o curta, com
genres = titles_sliced['genres'].str.split(',', 1, expand = True )
#generos.head()
titles_sliced['gerero_1'] = genres[0]
titles_sliced['gerero_2'] = genres[1]
titles_sliced.drop(columns = ['genres'], inplace = True)
titles_sliced.head(5)

C:\Users\fic\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\fic\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      tconst titleType            primaryTitle     gerero_1        gerero_2
0  tt0000001     short              Carmencita  Documentary           Short
1  tt0000002     short  Le clown et ses chiens    Animation           Short
2  tt0000003     short          Pauvre Pierrot    Animation  Comedy,Romance
3  tt0000004     short             Un bon bock    Animation           Short
4  tt0000005     short        Blacksmith Scene       Comedy           Short

In [151]:
titles_sliced.columns = ['tconst', 'tipo', 'titulo', 'genero', 'sub.genero']
titles_sliced.head()

      tconst   tipo                  titulo       genero      sub.genero
0  tt0000001  short              Carmencita  Documentary           Short
1  tt0000002  short  Le clown et ses chiens    Animation           Short
2  tt0000003  short          Pauvre Pierrot    Animation  Comedy,Romance
3  tt0000004  short             Un bon bock    Animation           Short
4  tt0000005  short        Blacksmith Scene       Comedy           Short

In [152]:
titles_rating_merge = titles_rating.merge(titles_sliced, left_on = 'tconst', right_on = 'tconst') # fazendo a jun√ß√£o das tabelas com Merge, utilizando a coluna TCONST como chave primaria   
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge.html?highlight=merge#pandas.merge
titles_rating_merge.head()

,tconst,averageRating,numVotes,tipo,titulo,genero,sub.genero
0,tt0000001,5.6,1550,short,Carmencita,Documentary,Short
1,tt0000002,6.1,186,short,Le clown et ses chiens,Animation,Short
2,tt0000003,6.5,1207,short,Pauvre Pierrot,Animation,"Comedy,Romance"
3,tt0000004,6.2,113,short,Un bon bock,Animation,Short
4,tt0000005,6.1,1934,short,Blacksmith Scene,Comedy,Short

In [161]:
titles_rating_merge.sort_values(by =['numVotes'], ascending=False).head(100)

,tconst,averageRating,numVotes,tipo,titulo,genero,sub.genero
80579,tt0111161,9.3,2159745,movie,The Shawshank Redemption,Drama,None
241008,tt0468569,9.0,2134602,movie,The Dark Knight,Action,"Crime,Drama"
515622,tt1375666,8.8,1892958,movie,Inception,Action,"Adventure,Sci-Fi"
96689,tt0137523,8.8,1725444,movie,Fight Club,Drama,None
80363,tt0110912,8.9,1695159,movie,Pulp Fiction,Crime,Drama
79501,tt0109830,8.8,1662609,movie,Forrest Gump,Drama,Romance
413358,tt0944947,9.4,1606096,tvSeries,Game of Thrones,Action,"Adventure,Drama"
94660,tt0133093,8.7,1554345,movie,The Matrix,Action,Sci-Fi
88334,tt0120737,8.8,1548920,movie,The Lord of the Rings: The Fellowship of the Ring,Adventure,"Drama,Fantasy"
111186,tt0167260,8.9,1533632,movie,The Lord of the Rings: The Return of the King,Adventure,"Drama,Fantasy"
44727,tt0068646,9.2,1482225,movie,The Godfather,Crime,Drama
509867,tt1345836,8.4,1421506,movie,The Dark Knight Rises,Action,Thriller
111187,tt0167261,8.7,1387208,movie,The Lord of the Rings: The Two Towers,Adventure,"Drama,Fantasy"
378552,tt0816692,8.6,1348184,movie,Interstellar,Adventure,"Drama,Sci-Fi"
83129,tt0114369,8.6,1327441,movie,Se7en,Crime,"Drama,Mystery"
403836,tt0903747,9.5,1280143,tvSeries,Breaking Bad,Crime,"Drama,Thriller"
596786,tt1853728,8.4,1249336,movie,Django Unchained,Drama,Western
113555,tt0172495,8.5,1246819,movie,Gladiator,Action,"Adventure,Drama"
201998,tt0372784,8.2,1225060,movie,Batman Begins,Action,Adventure
388847,tt0848228,8.0,1206913,movie,The Avengers,Action,"Adventure,Sci-Fi"
73829,tt0102926,8.6,1169847,movie,The Silence of the Lambs,Crime,"Drama,Thriller"
197060,tt0361748,8.3,1162262,movie,Inglourious Basterds,Adventure,"Drama,War"
51609,tt0076759,8.6,1147264,movie,Star Wars: Episode IV - A New Hope,Action,"Adventure,Fantasy"
88396,tt0120815,8.6,1143793,movie,Saving Private Ryan,Drama,War
78033,tt0108052,8.9,1120297,movie,Schindler's List,Biography,"Drama,History"
217274,tt0407887,8.5,1104064,movie,The Departed,Crime,"Drama,Thriller"
246819,tt0482571,8.5,1095266,movie,The Prestige,Drama,"Mystery,Sci-Fi"
54964,tt0080684,8.7,1078754,movie,Star Wars: Episode V - The Empire Strikes Back,Action,"Adventure,Fantasy"
424947,tt0993846,8.2,1069874,movie,The Wolf of Wall Street,Biography,"Crime,Drama"
253005,tt0499549,7.8,1066615,movie,Avatar,Action,"Adventure,Fantasy"
...,...,...,...,...,...,...,...
649053,tt2267998,8.1,784465,movie,Gone Girl,Drama,"Mystery,Thriller"
126486,tt0198781,8.0,760273,movie,"Monsters, Inc.",Adventure,"Animation,Comedy"
429650,tt1010048,8.0,759588,movie,Slumdog Millionaire,Drama,Romance
61356,tt0088247,8.0,751700,movie,The Terminator,Action,Sci-Fi
154897,tt0264464,8.1,745335,movie,Catch Me If You Can,Biography,"Crime,Drama"
67160,tt0095016,8.2,735223,movie,Die Hard,Action,Thriller
130653,tt0208092,8.3,734562,movie,Snatch,Comedy,Crime
532643,tt1475582,9.1,733933,tvSeries,Sherlock,Crime,"Drama,Mystery"
53318,tt0078748,8.4,733661,movie,Alien,Horror,Sci-Fi
403805,tt0903624,7.8,728476,movie,The Hobbit: An Unexpected Journey,Adventure,"Family,Fantasy"
528899,tt1454468,7.7,725671,movie,Gravity,Drama,"Sci-Fi,Thriller"
769375,tt4154756,8.5,725112,movie,Avengers: Infinity War,Action,"Adventure,Sci-Fi"
214884,tt0401792,8.0,721717,movie,Sin City,Crime,Thriller
117191,tt0180093,8.3,716729,movie,Requiem for a Dream,Drama,None
78611,tt0108778,8.9,715485,tvSeries,Friends,Comedy,Romance
500204,tt1300854,7.2,711617,movie,Iron Man 3,Action,"Adventure,Sci-Fi"
146970,tt0246578,8.0,708866,movie,Donnie Darko,Drama,"Sci-Fi,Thriller"
479730,tt1201607,8.1,708388,movie,Harry Potter and the Deathly Hallows: Part 2,Adventure,"Drama,Fantasy"
43203,tt0066921,8.3,707611,movie,A Clockwork Orange,Crime,"Drama,Sci-Fi"
228642,tt0435761,8.3,707372,movie,Toy Story 3,Adventure,"Animation,Comedy"
220585,tt0416449,7.7,702798,movie,300,Action,"Drama,Fantasy"
372970,tt0800369,7.0,702396,movie,Thor,Action,"Adventure,Fantasy"
742704,tt3659388,8.0,701746,movie,The Martian,Adventure,"Drama,Sci-Fi"
567765,tt1675434,8.5,698385,movie,The Intouchables,Biography,"Comedy,Drama"
665182,tt2395427,7.3,688963,movie,Avengers: Age of Ultron,Action,"Adventure,Sci-Fi"
237413,tt0458339,6.9,688918,movie,Captain America: The First Avenger,Action,"Adventure,Sci-Fi"
595152,tt1843866,7.7,687645,movie,Captain America: The Winter Soldier,Action,"Adventure,Sci-Fi"
59681,tt0086250,8.3,682563,movie,Scarface,Crime,Drama
480508,tt1205489,8.1,682498,movie,Gran Torino,Drama,None
464629,tt1119646,7.7,682340,movie,The Hangover,Comedy,None

In [173]:
top = titles_rating_merge[(titles_rating_merge['numVotes'] > 50000)].sort_values(by =['averageRating'], ascending=False).head(50)
top

,tconst,averageRating,numVotes,tipo,titulo,genero,sub.genero
652909,tt2301451,10.0,108546,tvEpisode,Ozymandias,Crime,"Drama,Thriller"
754712,tt3866850,9.9,85697,tvEpisode,Hardhome,Action,"Adventure,Drama"
652911,tt2301455,9.9,78605,tvEpisode,Felina,Crime,"Drama,Thriller"
776333,tt4283094,9.9,126931,tvEpisode,The Winds of Winter,Action,"Adventure,Drama"
637977,tt2178784,9.9,84994,tvEpisode,The Rains of Castamere,Action,"Adventure,Drama"
776332,tt4283088,9.9,182843,tvEpisode,Battle of the Bastards,Action,"Adventure,Drama"
852024,tt5775846,9.8,77872,tvEpisode,The Spoils of War,Action,"Adventure,Drama"
776326,tt4283028,9.7,62609,tvEpisode,The Door,Action,"Adventure,Drama"
120294,tt0185906,9.5,337036,tvMiniSeries,Band of Brothers,Action,"Drama,History"
403836,tt0903747,9.5,1280143,tvSeries,Breaking Bad,Crime,"Drama,Thriller"
923861,tt7366338,9.5,382356,tvMiniSeries,Chernobyl,Drama,"History,Thriller"
837163,tt5491994,9.5,81416,tvMiniSeries,Planet Earth II,Documentary,None
852030,tt5775874,9.5,56493,tvEpisode,The Dragon and the Wolf,Action,"Adventure,Drama"
371428,tt0795176,9.4,154552,tvMiniSeries,Planet Earth,Documentary,None
413358,tt0944947,9.4,1606096,tvSeries,Game of Thrones,Action,"Adventure,Drama"
175170,tt0306414,9.3,255448,tvSeries,The Wire,Crime,"Drama,Thriller"
694700,tt2861424,9.3,300311,tvSeries,Rick and Morty,Adventure,"Animation,Comedy"
665217,tt2395695,9.3,100767,tvSeries,Cosmos,Documentary,None
80579,tt0111161,9.3,2159745,movie,The Shawshank Redemption,Drama,None
98720,tt0141842,9.2,264322,tvSeries,The Sopranos,Crime,Drama
220960,tt0417299,9.2,201565,tvSeries,Avatar: The Last Airbender,Action,"Adventure,Animation"
44727,tt0068646,9.2,1482225,movie,The Godfather,Crime,Drama
511908,tt1355642,9.1,96477,tvSeries,Fullmetal Alchemist: Brotherhood,Action,"Adventure,Animation"
593202,tt1831164,9.1,84368,tvSeries,Leyla and Mecnun,Adventure,"Comedy,Drama"
852028,tt5775864,9.1,57020,tvEpisode,Beyond the Wall,Action,"Adventure,Drama"
532643,tt1475582,9.1,733933,tvSeries,Sherlock,Crime,"Drama,Mystery"
173723,tt0303461,9.0,231153,tvSeries,Firefly,Adventure,"Drama,Sci-Fi"
30884,tt0052520,9.0,64157,tvSeries,The Twilight Zone,Drama,"Fantasy,Horror"
659454,tt2356777,9.0,458215,tvSeries,True Detective,Crime,"Drama,Mystery"
397307,tt0877057,9.0,196475,tvSeries,Death Note,Animation,"Crime,Drama"
74182,tt0103359,9.0,78473,tvSeries,Batman: The Animated Series,Action,"Adventure,Animation"
241008,tt0468569,9.0,2134602,movie,The Dark Knight,Action,"Crime,Drama"
914961,tt7137906,9.0,52985,tvMiniSeries,When They See Us,Biography,"Drama,History"
47237,tt0071562,9.0,1032110,movie,The Godfather: Part II,Crime,Drama
854299,tt5813916,9.0,101817,movie,The Mountain II,Action,"Drama,War"
787708,tt4508902,8.9,93713,tvSeries,One Punch Man,Action,"Animation,Comedy"
691705,tt2802850,8.9,285994,tvSeries,Fargo,Crime,"Drama,Thriller"
78611,tt0108778,8.9,715485,tvSeries,Friends,Comedy,Romance
734798,tt3530232,8.9,70993,tvSeries,Last Week Tonight with John Oliver,Comedy,"News,Talk-Show"
78033,tt0108052,8.9,1120297,movie,Schindler's List,Biography,"Drama,History"
111186,tt0167260,8.9,1533632,movie,The Lord of the Rings: The Return of the King,Adventure,"Drama,Fantasy"
80363,tt0110912,8.9,1695159,movie,Pulp Fiction,Crime,Drama
28825,tt0050083,8.9,617607,movie,12 Angry Men,Drama,None
598609,tt1865718,8.9,58030,tvSeries,Gravity Falls,Action,"Adventure,Animation"
132983,tt0213338,8.9,78838,tvSeries,Cowboy Bebop,Action,"Adventure,Animation"
81344,tt0112130,8.9,69860,tvMiniSeries,Pride and Prejudice,Drama,Romance
669242,tt2442560,8.8,240336,tvSeries,Peaky Blinders,Crime,Drama
70480,tt0098904,8.8,233018,tvSeries,Seinfeld,Comedy,None
242712,tt0472954,8.8,175871,tvSeries,It's Always Sunny in Philadelphia,Comedy,None
243688,tt0475784,8.8,366319,tvSeries,Westworld,Drama,"Mystery,Sci-Fi"

In [174]:
top_1 = top.groupby(['tipo','genero']).agg({'numVotes':'sum'})
top_1

                          numVotes
tipo         genero
movie        Action        2236419
             Adventure     1533632
             Biography     1120297
             Crime         4209494
             Drama         2777352
tvEpisode    Action         734459
             Crime          187151
tvMiniSeries Action         337036
             Biography       52985
             Documentary    235968
             Drama          452216
tvSeries     Action        2213192
             Adventure      615832
             Animation      196475
             Comedy        1195367
             Crime         3518391
             Documentary    100767
             Drama          430476

In [175]:
top_pcts = top_1.groupby(level = 0).apply(lambda x: 100 * x / float(x.sum()))
top_pcts.sort_values(by = ['numVotes'], ascending = False)

                           numVotes
tipo         genero
tvEpisode    Action       79.693037
tvSeries     Crime        42.541455
tvMiniSeries Drama        41.941560
movie        Crime        35.441822
tvMiniSeries Action       31.258991
tvSeries     Action       26.760075
movie        Drama        23.383907
tvMiniSeries Documentary  21.885263
tvEpisode    Crime        20.306963
movie        Action       18.829523
tvSeries     Comedy       14.453383
movie        Adventure    12.912410
             Biography     9.432337
tvSeries     Adventure     7.446128
             Drama         5.204957
tvMiniSeries Biography     4.914186
tvSeries     Animation     2.375612
             Documentary   1.218391

In [179]:
top_2 = top.groupby(['tipo','genero']).agg({'averageRating':'mean', 'numVotes':'sum'})
top_2

                          averageRating  numVotes
tipo         genero
movie        Action            9.000000   2236419
             Adventure         8.900000   1533632
             Biography         8.900000   1120297
             Crime             9.033333   4209494
             Drama             9.100000   2777352
tvEpisode    Action            9.712500    734459
             Crime             9.950000    187151
tvMiniSeries Action            9.500000    337036
             Biography         9.000000     52985
             Documentary       9.450000    235968
             Drama             9.200000    452216
tvSeries     Action            9.057143   2213192
             Adventure         9.133333    615832
             Animation         9.000000    196475
             Comedy            8.850000   1195367
             Crime             9.114286   3518391
             Documentary       9.300000    100767
             Drama             8.900000    430476